// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb8x_0eC1trNwdqJRbQbQfZ2IxcVBQ6XU',
    appId: '1:445939095970:web:cbef2cd00196ffbf323afb',
    messagingSenderId: '445939095970',
    projectId: 'lawer-cd736',
    authDomain: 'lawer-cd736.firebaseapp.com',
    storageBucket: 'lawer-cd736.appspot.com',
    measurementId: 'G-7HVKTLYHQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwn2hPn7z677U9agu1alTplbCFMhbNOpw',
    appId: '1:445939095970:android:a0a336b3710a1e20323afb',
    messagingSenderId: '445939095970',
    projectId: 'lawer-cd736',
    storageBucket: 'lawer-cd736.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp4zXY3BXE5E_o4NkxWJf6ksnpUXMPBtk',
    appId: '1:445939095970:ios:9474e33474ea82e7323afb',
    messagingSenderId: '445939095970',
    projectId: 'lawer-cd736',
    storageBucket: 'lawer-cd736.appspot.com',
    iosClientId: '445939095970-pguhiauso078fjnplu2947ker2mb2j87.apps.googleusercontent.com',
    iosBundleId: 'com.example.lawyer',
  );
}
